context.h: add missing stdarg.h include
Fix compilation error on uclibc based systems:

==
In file included from idbm.c:59:0:
context.h:27:25: error: unknown type name ‘va_list’
     const char *format, va_list args);
                         ^
<builtin>: recipe for target 'idbm.o' failed
make[1]: *** [idbm.o] Error 1
==

Signed-off-by: Floris Bos <bos@je-eigen-domein.nl>